{% set name = "qlayers" %}
{% set version = "1.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alexdaniel654/qlayers/archive/v{{ version }}.tar.gz
  sha256: c98318e65965fe457f0f2a74e031cf432df924dd3dcbc808366a9df4604303a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - nibabel
    - numpy
    - pandas
    - pytest
    - rtree
    - scikit-image
    - tqdm
    - trimesh

test:
  source_files:
    - qlayers
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  imports:
    - qlayers
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/alexdaniel654/qlayers
  summary: Quantitative layer analysis for renal MRI
  license: GPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://qlayers.readthedocs.io/
  dev_url: https://github.com/alexdaniel654/qlayers

extra:
  recipe-maintainers:
    - alexdaniel654
